/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <ApplicationCode.h>
#include <LED_Driver.h>
#include <STM32F429i.h>
#include <scheduler.h>
#include <GPIO_Driver.h>
#include <stdio.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
  uint32_t events2run = 0;

  // Initialize the application, which sets up peripherals, LEDs, buttons, etc.
  Application_Init();

  /* Loop forever */
  for (;;){
    // Fetch the events that are scheduled to run
    events2run = getScheduledEvents();
#if DAUL_TIMER_USAGE == 0
    if (events2run & TOGGLE_EVENT){
      RedToggle();
    }

#endif

    if (events2run & DELAYEVENT){
      delayProto(DEFAULT_VAL);
    }

#ifndef USE_INTERRUPT_FOR_BUTTON
    if (events2run & POLLEVENT){
      executeButtonPollingRoutine(); // Handle button polling if interrupts are not used
    }
#endif
  }
}
